### ISSUE TITLE
npm start之后加载一段之后出现这个

### ISSUE THREAD

**Issue by Nekoer** [LoveLiveSunshine/pixiv.moe#28] opened 2019-02-09 13:11 UTC
ERROR in ./src/containers/GalleryContainer.js
Module not found: Error: Can't resolve '@material-ui/docs/svgIcons/Github' in '/www/wwwroot/pic.hcyacg.com/src/containers'
 @ ./src/containers/GalleryContainer.js 55:0-59
 @ ./src/containers/AppContainer.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:23333 webpack/hot/dev-server babel-polyfill react-hot-loader/patch ./src/index

**Comment by kokororin** [comment] 2019-02-09 14:03
yarn install

**Comment by Nekoer** [comment] 2019-02-09 14:10
![72 3ieewbjkf 2e g_1 h n](https://user-images.githubusercontent.com/32485369/52521777-80059e80-2cb7-11e9-811b-8fe554cc34a2.png)
安装过了，然后启动还是有这个

**Comment by kokororin** [comment] 2019-02-09 14:24
Don't use `npm instal`

**Comment by Nekoer** [comment] 2019-02-09 15:11
不明白是我服务器问题还是我操作问题，我使用的是centos系统
操作步骤如下：
1：下载pixiv.moe压缩包解压至根目录
2：安装yarn
使用的以下命令
`curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo`
然后去下载nodejs的linux安装压缩包到服务器进行解压
3：yarn install
4：npm start启动
步骤下来然后就会出现之前的截图问题
我又试了npm test出现了
![pwe8 kxvflw 56 ybc2 f](https://user-images.githubusercontent.com/32485369/52522404-01612f00-2cc0-11e9-8e01-84ed558a0802.png)

**Comment by kirainmoe** [comment] 2019-02-09 18:09
> ERROR in ./src/containers/GalleryContainer.js
> Module not found: Error: Can't resolve '@material-ui/docs/svgIcons/Github' in '/www/wwwroot/pic.hcyacg.com/src/containers'
> @ ./src/containers/GalleryContainer.js 55:0-59
> @ ./src/containers/AppContainer.js
> @ ./src/index.js
> @ multi (webpack)-dev-server/client?http://0.0.0.0:23333 webpack/hot/dev-server babel-polyfill react-hot-loader/patch ./src/index

It isn't shown in Windows / macOS, but it is confirmed in my local Arch Linux environment. I have already submitted a PR to fix the problem. To fix it, you can run `git pull` after my PR is merged. Or you can fix it manually. See what is changed in #29.



> 不明白是我服务器问题还是我操作问题，我使用的是centos系统
> 操作步骤如下：
> 1：下载pixiv.moe压缩包解压至根目录
> 2：安装yarn
> 使用的以下命令
> `curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo`
> 然后去下载nodejs的linux安装压缩包到服务器进行解压
> 3：yarn install
> 4：npm start启动
> 步骤下来然后就会出现之前的截图问题
> 我又试了npm test出现了
> ![pwe8 kxvflw 56 ybc2 f](https://user-images.githubusercontent.com/32485369/52522404-01612f00-2cc0-11e9-8e01-84ed558a0802.png)

You should have headless Chrome framework(puppeteer) installed correctly before you run `yarn test` or `npm run test`. From the logs shown in the screenshot you could tell that some libs were failed to be installed. It is because that unlike Ubuntu/Debian, CentOS doesn't install dependencies for puppeteer. To fix that you should install dependencies manually, or try the solution found in Google: https://github.com/GoogleChrome/puppeteer/issues/560#issuecomment-325245136

But I think you may not need to run a test as these unit tests are created for developers to validate that the project performs as designed.

**Closed** 2019-02-10 02:17 UTC

**Comment by Nekoer** [comment] 2019-02-10 11:50
之前的问题解决了，但是又出现了新的问题
![4p_as vn o _6de2zkw a](https://user-images.githubusercontent.com/32485369/52533307-eb5d7800-2d6c-11e9-91b0-7fd883b6faf5.png)
另外最后的Log附在下面
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.5.0
3 info using node@v11.9.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle pixiv.moe@1.4.0~prestart: pixiv.moe@1.4.0
6 info lifecycle pixiv.moe@1.4.0~start: pixiv.moe@1.4.0
7 verbose lifecycle pixiv.moe@1.4.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle pixiv.moe@1.4.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/www/wwwroot/pixiv.moe/node_modules/.bin:/root/.yarn/bin:/root/.config/yarn/global/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
9 verbose lifecycle pixiv.moe@1.4.0~start: CWD: /www/wwwroot/pixiv.moe
10 silly lifecycle pixiv.moe@1.4.0~start: Args: [ '-c',
10 silly lifecycle   'cross-env NODE_ENV=development webpack-dev-server --progress --config build/webpack.config.js' ]
11 silly lifecycle pixiv.moe@1.4.0~start: Returned: code: 1  signal: null
12 info lifecycle pixiv.moe@1.4.0~start: Failed to exec start script
13 verbose stack Error: pixiv.moe@1.4.0 start: `cross-env NODE_ENV=development webpack-dev-server --progress --config build/webpack.config.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:197:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:197:13)
13 verbose stack     at maybeClose (internal/child_process.js:978:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
14 verbose pkgid pixiv.moe@1.4.0
15 verbose cwd /www/wwwroot/pixiv.moe
16 verbose Linux 3.10.0-693.11.6.el7.x86_64
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v11.9.0
19 verbose npm  v6.5.0
20 error code ELIFECYCLE
21 error errno 1
22 error pixiv.moe@1.4.0 start: `cross-env NODE_ENV=development webpack-dev-server --progress --config build/webpack.config.js`
22 error Exit status 1
23 error Failed at the pixiv.moe@1.4.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by kirainmoe** [comment] 2019-02-10 12:06
@Nekoer  `yarn dev` or `npm run dev` will open the default browser of your current system. Your server doesn't support that. To fix it you should disable `open-browser-webpack-plugin` in `build/webpack.config.dev.js`. Delete https://github.com/LoveLiveSunshine/pixiv.moe/blob/98f50513d100e46c955ce3e88412f724fa1a6f94/build/webpack.config.dev.js#L4 and https://github.com/LoveLiveSunshine/pixiv.moe/blob/98f50513d100e46c955ce3e88412f724fa1a6f94/build/webpack.config.dev.js#L41 two lines.
